# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: minimum_viable_product 0.6.2 ruby lib

Gem::Specification.new do |s|
  s.name = "minimum_viable_product"
  s.version = "0.6.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ian Hunter"]
  s.date = "2016-12-08"
  s.description = "Built for Developers. Ideal for MVPs, product ideation and validation."
  s.email = "ianhunter@gmail.com"
  s.executables = ["mvp", "rails"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/mvp/application.js",
    "app/assets/stylesheets/mvp/application.scss",
    "app/controllers/concerns/minimum_viable_product/analytics_concern.rb",
    "app/controllers/concerns/minimum_viable_product/seo_concern.rb",
    "app/controllers/concerns/minimum_viable_product/session_concern.rb",
    "app/controllers/minimum_viable_product/analytics_controller.rb",
    "app/controllers/minimum_viable_product/seo_controller.rb",
    "app/controllers/minimum_viable_product/styleguide_controller.rb",
    "app/helpers/minimum_viable_product/body_helper.rb",
    "app/helpers/minimum_viable_product/bootstrap_helper.rb",
    "app/helpers/minimum_viable_product/styleguide_helper.rb",
    "app/models/concerns/minimum_viable_product/slugification.rb",
    "app/views/layouts/minimum_viable_product/_instrumentation.html.erb",
    "app/views/layouts/minimum_viable_product/_meta.html.erb",
    "app/views/layouts/minimum_viable_product/application.html.erb",
    "app/views/minimum_viable_product/styleguide/_example.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_buttons.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_forms.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_header.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_panels.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_tables.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_typography.html.erb",
    "app/views/minimum_viable_product/styleguide/elements/_grouping.html.erb",
    "app/views/minimum_viable_product/styleguide/elements/partials/_row_groups_of.html.erb",
    "app/views/minimum_viable_product/styleguide/index.html.erb",
    "app/views/minimum_viable_product/styleguide/layouts/basic.html.erb",
    "app/views/minimum_viable_product/styleguide/layouts/carousel.html.erb",
    "app/views/minimum_viable_product/styleguide/layouts/cover.html.erb",
    "assets/js/application.js",
    "assets/js/init/controllers.js",
    "assets/js/init/forms.js",
    "bin/mvp",
    "bin/rails",
    "config/initializers/assets.rb",
    "config/initializers/canonical_host.rb",
    "config/initializers/cloudinary.rb",
    "config/initializers/geocoder.rb",
    "config/initializers/iteration.rb",
    "config/initializers/project.rb",
    "config/initializers/rollbar.rb",
    "config/initializers/routing.rb",
    "config/initializers/segment.rb",
    "config/initializers/spoof_ip.rb",
    "config/initializers/ssl.rb",
    "config/routes.rb",
    "lib/minimum_viable_product.rb",
    "lib/minimum_viable_product/engine.rb",
    "lib/minimum_viable_product/ext/nil.rb",
    "lib/minimum_viable_product/ext/string.rb",
    "lib/tasks/sitemap.rake",
    "mvp.gemspec",
    "package.json",
    "test/helper.rb",
    "test/test_minimum_viable_product.rb"
  ]
  s.homepage = "http://github.com/ian/minimum_viable_product"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "The start-to-finish 3 minute product platform"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

