# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: minimum_viable_product 0.7.11 ruby lib

Gem::Specification.new do |s|
  s.name = "minimum_viable_product"
  s.version = "0.7.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ian Hunter"]
  s.date = "2017-02-22"
  s.description = "Built for Developers. Ideal for MVPs, product ideation and validation."
  s.email = "ianhunter@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/mvp/application.js",
    "app/assets/stylesheets/mvp/application.scss",
    "app/controllers/concerns/minimum_viable_product/analytics_concern.rb",
    "app/controllers/concerns/minimum_viable_product/seo_concern.rb",
    "app/controllers/concerns/minimum_viable_product/session_concern.rb",
    "app/controllers/minimum_viable_product/analytics_controller.rb",
    "app/controllers/minimum_viable_product/seo_controller.rb",
    "app/controllers/minimum_viable_product/styleguide_controller.rb",
    "app/helpers/minimum_viable_product/body_helper.rb",
    "app/helpers/minimum_viable_product/bootstrap_helper.rb",
    "app/helpers/minimum_viable_product/styleguide_helper.rb",
    "app/models/concerns/minimum_viable_product/slugification.rb",
    "app/views/layouts/minimum_viable_product/_instrumentation.html.erb",
    "app/views/layouts/minimum_viable_product/_meta.html.erb",
    "app/views/layouts/minimum_viable_product/application.html.erb",
    "app/views/minimum_viable_product/styleguide/_example.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_buttons.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_forms.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_header.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_panels.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_tables.html.erb",
    "app/views/minimum_viable_product/styleguide/bootstrap/_typography.html.erb",
    "app/views/minimum_viable_product/styleguide/elements/_grouping.html.erb",
    "app/views/minimum_viable_product/styleguide/elements/partials/_row_groups_of.html.erb",
    "app/views/minimum_viable_product/styleguide/index.html.erb",
    "app/views/minimum_viable_product/styleguide/layouts/basic.html.erb",
    "app/views/minimum_viable_product/styleguide/layouts/carousel.html.erb",
    "app/views/minimum_viable_product/styleguide/layouts/cover.html.erb",
    "assets/js/application.js",
    "assets/js/init/controllers.js",
    "assets/js/init/forms.js",
    "bin/mvp",
    "bin/rails",
    "config/initializers/assets.rb",
    "config/initializers/canonical_host.rb",
    "config/initializers/cloudinary.rb",
    "config/initializers/geocoder.rb",
    "config/initializers/iteration.rb",
    "config/initializers/project.rb",
    "config/initializers/rollbar.rb",
    "config/initializers/routing.rb",
    "config/initializers/spoof_ip.rb",
    "config/initializers/ssl.rb",
    "config/routes.rb",
    "lib/minimum_viable_product.rb",
    "lib/minimum_viable_product/engine.rb",
    "lib/minimum_viable_product/ext/nil.rb",
    "lib/minimum_viable_product/ext/string.rb",
    "lib/tasks/sitemap.rake",
    "minimum_viable_product.gemspec",
    "mvp.gemspec",
    "package.json",
    "project/.gitignore",
    "project/Gemfile",
    "project/Gemfile.lock",
    "project/Procfile",
    "project/README.md",
    "project/Rakefile",
    "project/app/controllers/application_controller.rb",
    "project/app/controllers/conversions_controller.rb",
    "project/app/controllers/examples_controller.rb",
    "project/app/controllers/home_controller.rb",
    "project/app/decorators/.keep",
    "project/app/helpers/application_helper.rb",
    "project/app/mailers/.keep",
    "project/app/models/conversion.rb",
    "project/app/views/examples/index.html.erb",
    "project/app/views/examples/mustache.html.erb",
    "project/app/views/examples/mustache/template.mustache",
    "project/app/views/home/conversion.html.erb",
    "project/app/views/home/index.html.erb",
    "project/app/views/layouts/_header.html.erb",
    "project/app/views/layouts/_includes.html.erb",
    "project/app/views/layouts/application.html.erb",
    "project/app/views/layouts/modal.html.erb",
    "project/assets/images/.keep",
    "project/assets/images/favicon.ico",
    "project/assets/javascripts/controllers/home.coffee",
    "project/assets/javascripts/pack.js",
    "project/assets/stylesheets/config/variables.scss",
    "project/assets/stylesheets/layout/basic.scss",
    "project/assets/stylesheets/layout/carousel.scss",
    "project/assets/stylesheets/layout/cover.scss",
    "project/assets/stylesheets/lib/spacing.scss",
    "project/assets/stylesheets/skin/style.scss",
    "project/assets/stylesheets/style.scss",
    "project/bin/bundle",
    "project/bin/rails",
    "project/bin/rake",
    "project/bin/setup",
    "project/bin/spring",
    "project/config.ru",
    "project/config/application.rb",
    "project/config/boot.rb",
    "project/config/database.yml",
    "project/config/environment.rb",
    "project/config/environments/development.rb",
    "project/config/environments/production.rb",
    "project/config/environments/test.rb",
    "project/config/initializers/assets.rb",
    "project/config/initializers/backtrace_silencers.rb",
    "project/config/initializers/cookies_serializer.rb",
    "project/config/initializers/filter_parameter_logging.rb",
    "project/config/initializers/inflections.rb",
    "project/config/initializers/mime_types.rb",
    "project/config/initializers/mustache.rb",
    "project/config/initializers/rails_admin.rb",
    "project/config/initializers/session_store.rb",
    "project/config/initializers/simple_form.rb",
    "project/config/initializers/wrap_parameters.rb",
    "project/config/locales/en.yml",
    "project/config/locales/simple_form.en.yml",
    "project/config/routes.rb",
    "project/config/secrets.yml",
    "project/config/sitemap.rb",
    "project/db/migrate/20160728235100_create_conversions.rb",
    "project/db/schema.rb",
    "project/db/seeds.rb",
    "project/lib/assets/.keep",
    "project/lib/tasks/heroku.rake",
    "project/log/.keep",
    "project/log/development.log",
    "project/log/production.log",
    "project/package.json",
    "project/public/404.html",
    "project/public/422.html",
    "project/public/500.html",
    "project/public/assets/javascripts/448c34a56d699c29117adc64c43affeb.woff2",
    "project/public/assets/javascripts/89889688147bd7575d6327160d64e760.svg",
    "project/public/assets/javascripts/e18bbf611f2a2e43afc071aa2f4e1512.ttf",
    "project/public/assets/javascripts/f4769f9bdb7466be65088239c12046d1.eot",
    "project/public/assets/javascripts/fa2772327f55d8198301fdb8bcfc8158.woff",
    "project/public/assets/javascripts/pack.js",
    "project/public/assets/javascripts/pack.js.map",
    "project/public/assets/pack.js",
    "project/public/assets/style.css",
    "project/vendor/assets/javascripts/.keep",
    "project/vendor/assets/stylesheets/.keep",
    "project/webpack.config.js",
    "test/helper.rb",
    "test/test_minimum_viable_product.rb"
  ]
  s.homepage = "http://github.com/ian/minimum_viable_product"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "The start-to-finish 3 minute product platform"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<carrierwave>, [">= 0"])
      s.add_runtime_dependency(%q<cloudinary>, [">= 0"])
      s.add_runtime_dependency(%q<geocoder>, [">= 0"])
      s.add_runtime_dependency(%q<faraday>, [">= 0"])
      s.add_runtime_dependency(%q<fog>, [">= 0"])
      s.add_runtime_dependency(%q<fog-aws>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_runtime_dependency(%q<rack-canonical-host>, [">= 0"])
      s.add_runtime_dependency(%q<rack-ssl-enforcer>, [">= 0"])
      s.add_runtime_dependency(%q<rollbar>, [">= 0"])
      s.add_runtime_dependency(%q<sass-rails>, ["~> 5.0"])
      s.add_runtime_dependency(%q<sitemap_generator>, [">= 0"])
      s.add_runtime_dependency(%q<slack-notifier>, [">= 0"])
      s.add_development_dependency(%q<byebug>, [">= 0"])
      s.add_development_dependency(%q<better_errors>, [">= 0"])
      s.add_development_dependency(%q<binding_of_caller>, [">= 0"])
      s.add_development_dependency(%q<bullet>, [">= 0"])
      s.add_development_dependency(%q<semantic>, [">= 0"])
      s.add_development_dependency(%q<web-console>, ["~> 2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<carrierwave>, [">= 0"])
      s.add_dependency(%q<cloudinary>, [">= 0"])
      s.add_dependency(%q<geocoder>, [">= 0"])
      s.add_dependency(%q<faraday>, [">= 0"])
      s.add_dependency(%q<fog>, [">= 0"])
      s.add_dependency(%q<fog-aws>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<rack-canonical-host>, [">= 0"])
      s.add_dependency(%q<rack-ssl-enforcer>, [">= 0"])
      s.add_dependency(%q<rollbar>, [">= 0"])
      s.add_dependency(%q<sass-rails>, ["~> 5.0"])
      s.add_dependency(%q<sitemap_generator>, [">= 0"])
      s.add_dependency(%q<slack-notifier>, [">= 0"])
      s.add_dependency(%q<byebug>, [">= 0"])
      s.add_dependency(%q<better_errors>, [">= 0"])
      s.add_dependency(%q<binding_of_caller>, [">= 0"])
      s.add_dependency(%q<bullet>, [">= 0"])
      s.add_dependency(%q<semantic>, [">= 0"])
      s.add_dependency(%q<web-console>, ["~> 2.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<carrierwave>, [">= 0"])
    s.add_dependency(%q<cloudinary>, [">= 0"])
    s.add_dependency(%q<geocoder>, [">= 0"])
    s.add_dependency(%q<faraday>, [">= 0"])
    s.add_dependency(%q<fog>, [">= 0"])
    s.add_dependency(%q<fog-aws>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<rack-canonical-host>, [">= 0"])
    s.add_dependency(%q<rack-ssl-enforcer>, [">= 0"])
    s.add_dependency(%q<rollbar>, [">= 0"])
    s.add_dependency(%q<sass-rails>, ["~> 5.0"])
    s.add_dependency(%q<sitemap_generator>, [">= 0"])
    s.add_dependency(%q<slack-notifier>, [">= 0"])
    s.add_dependency(%q<byebug>, [">= 0"])
    s.add_dependency(%q<better_errors>, [">= 0"])
    s.add_dependency(%q<binding_of_caller>, [">= 0"])
    s.add_dependency(%q<bullet>, [">= 0"])
    s.add_dependency(%q<semantic>, [">= 0"])
    s.add_dependency(%q<web-console>, ["~> 2.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

