source 'https://rubygems.org'

ruby '2.3.1'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "algoliasearch-rails"
gem 'carrierwave', '0.11.2' # don't upgrade it'll break carrierwave-neo4j
gem 'client_side_validations'
gem 'client_side_validations-simple_form'
gem "dotenv-rails"
gem 'identicon'
gem 'jbuilder', '~> 2.5'
gem 'mustache'
gem 'mvpkit'#, path: '../../mvpkit'
gem 'pg'
gem 'postmark-rails'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.1'
gem 'rails_admin'
gem 'redis'
gem 'redis-namespace'
gem 'sidekiq'
gem 'simple_form'
gem 'statistics2'
gem 'stripe-rails', github: 'thefrontside/stripe-rails'
gem 'workflow'

# assets
gem 'font-awesome-sass'
gem 'jquery-turbolinks'
gem 'sprockets', github: 'rails/sprockets' # edge includes format_source_map bug fix
# # See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer'
# # gem 'therubyracer', platforms: :ruby
gem 'turbolinks', '~> 5'
gem 'uglifier'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'letter_opener'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
