source 'https://rubygems.org'

gem 'client_side_validations'
gem 'client_side_validations-simple_form'
gem "dotenv-rails"
gem "draper"
gem 'minimum_viable_product'#, path: '../minimum_viable_product'
gem 'pg'
# gem 'puma'
gem 'rails', '4.2.3'
gem "rails_admin"
gem 'smt_rails', git: 'git://github.com/railsware/smt_rails.git'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  gem 'byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem "semantic"

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
