source 'https://rubygems.org'

ruby '2.4.0'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "algoliasearch-rails"
gem 'carrierwave'
gem 'client_side_validations'
gem 'client_side_validations-simple_form'
gem "cloudinary"
gem 'devise'
# gem 'devise_invitable' # uncomment if you want to make it so users are invitable
gem "dotenv-rails"
gem 'faraday'
gem 'fog'
gem 'fog-aws'
gem "geocoder"
gem "hashie"
gem 'identicon'
gem 'jbuilder', '~> 2.5'
gem 'kaminari'
gem 'mustache'
gem 'mvpkit', '~> 1.1.1'#, path: '../../mvpkit'
gem 'pg'
gem 'postmark-rails'
gem 'puma', '~> 3.0'
gem "rack-canonical-host"
gem 'rack-ssl-enforcer'
gem 'rails', '~> 5.0.1'
gem 'ransack'
gem 'redis'
gem 'redis-namespace'
gem 'rollbar'
gem 'sidekiq'
gem 'simple_form'
gem 'sitemap_generator'
gem 'slack-notifier'
gem 'stripe-rails'
gem 'workflow'

# engines
gem 'admin', path: './app/engines/admin'

# assets
gem 'react-rails'
gem 'sass-rails'
gem 'sprockets'#, github: 'rails/sprockets' # edge includes format_source_map bug fix
gem 'turbolinks', '~> 5'
gem 'uglifier'
gem 'webpacker'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'letter_opener'
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem "bullet"
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console'
end
